name: Test this action

on:
  pull_request:
    paths-ignore:
      - '*.md'
  push:
    paths-ignore:
      - '*.md'

jobs:
  test:
    name: ${{ matrix.os }}
    runs-on: ${{ matrix.os }}

    if: github.event_name == 'push' || github.event.pull_request.head.repo.full_name != github.repository

    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        include:
          - os: ubuntu-latest
            command: xvfb-run -a diff-pdf
          - os: windows-latest
            command: diff-pdf.exe

    steps:
    - if: matrix.os == 'ubuntu-latest'
      run: sudo apt-get install at-spi2-core

    - uses: actions/checkout@v4

    - name: Build package
      run: |
        yarn install
        yarn run package

    - name: Setup diff-pdf
      uses: ./
      with:
        diff-pdf-version: '0.5'

    - name: Echo diff-pdf
      run: ${{ matrix.command }} --help
