name: Test this action

on:
  pull_request:
    paths-ignore:
      - "*.md"
  push:
    branches:
      - main
      - dev/**
    paths-ignore:
      - "*.md"

jobs:
  test:
    name: ${{ matrix.os }}
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        include:
          - os: ubuntu-24.04
            command: xvfb-run -a diff-pdf
          - os: ubuntu-22.04
            command: xvfb-run -a diff-pdf
          - os: windows-latest
            command: diff-pdf.exe

    steps:
      - if: ${{ startsWith(matrix.os, 'ubuntu-') }}
        run: sudo apt-get install at-spi2-core

      - uses: actions/checkout@v4

      - name: Build package
        run: |
          yarn install
          yarn run package

      - name: Setup diff-pdf
        uses: ./
        with:
          diff-pdf-version: "0.5.2"

      - name: Echo diff-pdf
        run: ${{ matrix.command }} --help
